package org.firebears.subsystems;

import org.firebears.RobotMap;
import org.firebears.commands.drive.DriveCommand;
import org.firebears.sensors.sharpIRRange;

import edu.wpi.first.wpilibj.Gyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * The Subsystem for driving the robot.
 */
public class Chassis extends Subsystem {

	public Chassis() {
		if (drive_gyro!=null) drive_gyro.reset();
	}

	SpeedController front_left = RobotMap.chassis_front_left_controller;
	SpeedController back_left = RobotMap.chassis_back_left_controller;
	SpeedController front_right = RobotMap.chassis_front_right_controller;
	SpeedController back_right = RobotMap.chassis_back_right_controller;

	boolean fieldOriented = false;

	RobotDrive robot_drive = RobotMap.chassis_robot_drive;
	Gyro drive_gyro = RobotMap.chassis_drive_gyro;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	public sharpIRRange leftsharpIRRange = RobotMap.leftsharpIRRange;
	public sharpIRRange rightsharpIRRange = RobotMap.rightsharpIRRange;
	public sharpIRRange farleftsharpIRRange = RobotMap.farleftsharpIRRange;
	public sharpIRRange farrightsharpIRRange = RobotMap.farrightsharpIRRange;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	/**
	 * Drive the chassis mecanum wheels.
	 * 
	 * @param strafe
	 *            x dimension speed, in the range -1.0 to 1.0.
	 * @param forward
	 *            y dimension movement, in the range -1.0 to 1.0.
	 * @param rotation
	 *            angular rotation, in the range -1.0 to 1.0.
	 */
	public void mechanumDrive(double strafe, double forward, double rotation) {
		double angle = ((RobotMap.chassis_drive_gyro!=null) && fieldOriented) 
				? RobotMap.chassis_drive_gyro.getAngle() 
				: 0.0;
				
		// double cosA = Math.cos(theta * (3.14159 / 180.0));
		// double sinA = Math.sin(theta * (3.14159 / 180.0));
		// strafe = strafe * cosA - forward * sinA;
		// forward = strafe * sinA + forward * cosA;

		// front_left.set(strafe + forward + rotation);
		// front_right.set((strafe + forward - rotation));
		// back_left.set(strafe - forward + rotation);
		// back_right.set((strafe - forward - rotation ));

		robot_drive.mecanumDrive_Cartesian(strafe, -1 * forward, rotation, angle);
	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		setDefaultCommand(new DriveCommand());
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}
	
	/**
	 * Set whether driving is oriented to the field, versus oriented to the
	 * robot.  Setting this to 'true' means that we will use the gyro to 
	 * determine which way is forward;  forward on the joystick will always
	 * mean forward down the field.
	 */
	public void setFieldOriented(boolean b)  {
		fieldOriented = b;
	}
}
