package org.firebears.subsystems;

import org.firebears.RobotMap;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 * The subsystem for controlling the grabber.  Controls the solenoids.
 */
public class Grabber extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Compressor compressor = RobotMap.grabbercompressor;

	private boolean open = true;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	public Grabber() {
		RobotMap.grabbersolenoid_left_close.set(false);
		RobotMap.grabbersolenoid_right_close.set(false);
		RobotMap.grabbersolenoid_left_open.set(true);
		RobotMap.grabbersolenoid_right_open.set(true);
		open = true;

	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void setGrabbers(boolean close_grabbers) {
		RobotMap.grabbersolenoid_left_close.set(close_grabbers);
		RobotMap.grabbersolenoid_right_close.set(close_grabbers);
		RobotMap.grabbersolenoid_left_open.set(!close_grabbers);
		RobotMap.grabbersolenoid_right_open.set(!close_grabbers);
		open = !close_grabbers;
	}
	public boolean isOpen(){
		return true;
	}
}
