// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.firebears.subsystems;

import org.firebears.RobotMap;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Grabber extends Subsystem {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid solenoid_left_open = RobotMap.grabbersolenoid_left_open;
	Solenoid solenoid_left_close = RobotMap.grabbersolenoid_left_close;
	Solenoid solenoid_right_open = RobotMap.grabbersolenoid_right_open;
	Solenoid solenoid_right_close = RobotMap.grabbersolenoid_right_close;
	Compressor compressor = RobotMap.grabbercompressor;

	private boolean open = true;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	public Grabber() {
		solenoid_left_close.set(false);
		solenoid_right_close.set(false);
		solenoid_left_open.set(true);
		solenoid_right_open.set(true);
		open = true;

	}

	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void setGrabbers(boolean close_grabbers) {
		solenoid_left_close.set(close_grabbers);
		solenoid_right_close.set(close_grabbers);
		solenoid_left_open.set(!close_grabbers);
		solenoid_right_open.set(!close_grabbers);
		open = !close_grabbers;
	}
	public boolean isOpen(){
		return open;
	}
}
