// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.firebears.subsystems;

import org.firebears.RobotMap;
import org.firebears.commands.*;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.networktables.NetworkTable;
import edu.wpi.first.wpilibj.networktables2.server.NetworkTableServer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Lights extends Subsystem {

	NetworkTable table;
	
	private final String[] ab = {
			"strip1", "strip2", "strip3"
	};
	
	public static final String PULSING_GREEN_ANIM = "PULSING_GREEN_ANIM";
	public static final String MOVING_BLUE_ANIM = "MOVING_BLUE_ANIM";
	public static final String FIRE_ANIM = "FIRE_ANIM";
	
	public static final String RANDOM_ANIM = "RANDOM";
	
	public Lights() {
		table = NetworkTable.getTable("lights");
		setStrip(0, PULSING_GREEN_ANIM);
		setStrip(1, MOVING_BLUE_ANIM);
		setStrip(2, FIRE_ANIM);
		for(int i = 0; i < 3; i++) {
			setLiftHeight(i, 0.0);
		}
	}
	
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        setDefaultCommand(new LightsCommand());
	}

    public void setStrip(int which, String anim) {
    	if(anim == RANDOM_ANIM) {
    		switch(table.getString(ab[which])) {
    			case PULSING_GREEN_ANIM:
    				anim = MOVING_BLUE_ANIM;
    				break;
    			case MOVING_BLUE_ANIM:
    				anim = FIRE_ANIM;
    				break;
    			case FIRE_ANIM:
    				anim = PULSING_GREEN_ANIM;
    				break;
    		}
    	}
        table.putString(ab[which], anim);
    }
    
    public void setLiftHeight(int which, double height) {
        table.putNumber(ab[which] + ".value", height);
    }
}

